#!/bin/bash
# Description: Sets up and starts the server for you
# Author: Chris Young (young.c.5690@gmail.com)
# Created: September 17th 2015

start=$(date +%s);

# Do the stuff.

printf "Setup completed in %i seconds.\n" $(echo "$(date +%s) - $start" | bc)

