default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: postgres
  port: 5432

development:
  <<: *default
  database: apg_challenge_development

test:
  <<: *default
  database: apg_challenge_test

production:
  <<: *default
  database: apg_challenge_production
