# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f0e5c6f74ae268a9a3a8cdcdb2491c8960ab9c5fc379717e20b8b0af5f907d8608c87f03ca9d4770110faadb8b44fea727c2d1a054168284ddb8db108718e72

test:
  secret_key_base: d11992b07a3d004959d090c444fd4a6ba474cf6349275da8afc1812ccebf3657a43cf617b8cb125754382fb4fc918da5f2e03d7d29b24bc9b135a350048fb905

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
