# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec5f850d52c89e030bb457c236e6ed72fe790d437654e4f996535ecf319ebe214882d3b957e5a9f0bad84b2e085f19b530abf0120f5ce7003423307426cee341

test:
  secret_key_base: 98e6ca0e5acf99d182f5a8cde4c7aede2b32db8c69b549b6f9f8426b6f95af0b43b383a5176ccaea427d9e09648a4e0ab6e48fef5bd6a677b3bab889d12d862d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
